/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estacionamiento.controlador;


import com.formdev.flatlaf.FlatLightLaf;
import estacionamiento.vista.LoginMain;
import estacionamiento.vista.MapaEstacionamiento;
import estacionamiento.vista.PanelAdministracion;
import estacionamiento.vista.PanelEstadisticasGrafico;
import estacionamiento.vista.TemaUtil;
import estacionamiento.vista.VentanaCamara;



import javax.swing.JOptionPane;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Fernando Cruz
 */
public class Principal extends javax.swing.JFrame {

    private MapaEstacionamiento mapaEstacionamiento;
    private String userRole; // Variable para almacenar el rol del usuario
    private PanelEstadisticasGrafico panelEstadisticasGrafico;
    
    

    
    public Principal(String userRole) {
        this.userRole = userRole; // Asigna el rol del usuario
        TemaUtil.cargarConfiguracion(); // Cargar configuración antes de inicializar componentes
        TemaUtil.aplicarTema(this); // Aplicar el tema cargado antes de crear la interfaz
       
        initComponents();
        agregarMapaEstacionamiento();
        agregarPanelEstadisticasGrafico(); // Añadir el nuevo panel de estadísticas
        configurarPestañas();
    }

    private void agregarMapaEstacionamiento() {
        mapaEstacionamiento = new MapaEstacionamiento();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(mapaEstacionamiento, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    private void agregarPanelEstadisticasGrafico() {
        panelEstadisticasGrafico = new PanelEstadisticasGrafico();
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(panelEstadisticasGrafico, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    
    private void agregarPanelAdministracion() {
        PanelAdministracion panelAdministracion = new PanelAdministracion();
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(panelAdministracion, java.awt.BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }
    
    private void configurarPestañas() {
        if (!userRole.equals("administrador")) {
            jTabbedPane1.setEnabledAt(1, false); // Deshabilitar pestaña "Estadística"
            jTabbedPane1.setEnabledAt(2, false); // Deshabilitar pestaña "Panel de Administración"
        }else {
            agregarPanelAdministracion(); // Agregar panel de administración solo para administradores
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cambiarTema = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Estacionamiento");
        setMinimumSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        btnRegistrar.setText("Registrar Entrada de Vehiculo");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(5, 10, 5, 5));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2);

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel4);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel5);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6);

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel7);

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel8);

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel9);

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10);

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel12);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel13);

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel14);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel15);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel16);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel17);

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel18);

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel19);

        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel20);

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel21);

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel22);

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel23);

        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel24);

        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel25);

        jTabbedPane1.addTab("Mapa Estacionamiento", jPanel1);
        jTabbedPane1.addTab("Estadística", jPanel2);
        jTabbedPane1.addTab("Administración", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercr\\Downloads\\Iconos\\configuraciones.png")); // NOI18N

        cambiarTema.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cambiarTema.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        cambiarTema.setText("Cambiar tema");
        cambiarTema.setIconTextGap(0);
        cambiarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTemaActionPerformed(evt);
            }
        });
        jMenu1.add(cambiarTema);

        cerrarSesion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        cerrarSesion.setText("Cerrar sesión");
        cerrarSesion.setIconTextGap(0);
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(cerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        registrarEntradaVehiculo();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cambiarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTemaActionPerformed
        String[] opciones = {"Flat Light", "Flat Dark", "Arc Dark Orange", "Material Design Dark", "Monokai Pro", "Solarized Light", "Gradiano Midnight Blue"};
        int temaIndex = 0;
        for (int i = 0; i < opciones.length; i++) {
            if (opciones[i].equals(TemaUtil.getTemaActual())) {
                temaIndex = i;
                break;
            }
        }

        String temaSeleccionado = (String) JOptionPane.showInputDialog(
            this,
            "Selecciona el tema",
            "Cambiar Tema",
            JOptionPane.PLAIN_MESSAGE,
            null,
            opciones,
            opciones[temaIndex] // Tema actual como opción por defecto
        );

        if (temaSeleccionado != null && !temaSeleccionado.equals(TemaUtil.getTemaActual())) {
            TemaUtil.setTemaActual(temaSeleccionado);
            TemaUtil.aplicarTema(this);
            TemaUtil.guardarConfiguracion(); // Guardar configuración al cambiar el tema
        }
    }//GEN-LAST:event_cambiarTemaActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
         // Cerrar la ventana principal y mostrar la ventana de login
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LoginMain loginFrame = new LoginMain();
                loginFrame.setVisible(true);
            }
        });       
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void registrarEntradaVehiculo() {
        VentanaCamara ventanaCamara = new VentanaCamara(this.mapaEstacionamiento);
        ventanaCamara.setVisible(true);
       
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        TemaUtil.cargarConfiguracion();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Principal principal = new Principal("usuario");
            TemaUtil.aplicarTema(principal);
            principal.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JMenuItem cambiarTema;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
