/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estacionamiento.vista;



/**
 *
 * @author ericg
 */
public class LoginMain extends javax.swing.JFrame {


    public LoginMain() {
        TemaUtil.cargarConfiguracion(); // Cargar configuración antes de inicializar componentes
        TemaUtil.aplicarTema(this); // Aplicar el tema cargado antes de crear la interfaz
        
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login1 = new estacionamiento.vista.login();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 260));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login1.setMaximumSize(new java.awt.Dimension(420, 260));
        login1.setMinimumSize(new java.awt.Dimension(420, 260));
        getContentPane().add(login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Cargar configuración y aplicar el tema antes de inicializar la GUI
        TemaUtil.cargarConfiguracion();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginMain loginMain = new LoginMain();
                TemaUtil.aplicarTema(loginMain);
                loginMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private estacionamiento.vista.login login1;
    // End of variables declaration//GEN-END:variables
}
