/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package estacionamiento.vista;

import estacionamiento.controlador.Principal;
import estacionamiento.modelo.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ericg
 */
public class login extends javax.swing.JPanel {

     private String temaActual;
     
    public login() {
        
        initComponents();
        lblOcultar.setVisible(false);
        lblOcultar1.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_usuario = new javax.swing.JDialog();
        txtCorreo_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar_usuario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblOcultar = new javax.swing.JLabel();
        txtContra_usuario = new javax.swing.JPasswordField();
        lblVer = new javax.swing.JLabel();
        dialog_admin = new javax.swing.JDialog();
        txtCorreo_admin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAceptar_admin = new javax.swing.JButton();
        lblOcultar1 = new javax.swing.JLabel();
        lblVer1 = new javax.swing.JLabel();
        txtContra_admin = new javax.swing.JPasswordField();
        dialog_registro_usuario = new javax.swing.JDialog();
        Nombre_usuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Correo_usuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Contra_usuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Contra_usuario2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRegistrar_usuario = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mostrar_1 = new javax.swing.JLabel();
        ocultar_1 = new javax.swing.JLabel();
        ocultar_2 = new javax.swing.JLabel();
        mostrar_2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_usuario = new javax.swing.JButton();
        btn_administrador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        dialog_usuario.setMinimumSize(new java.awt.Dimension(329, 343));
        dialog_usuario.setResizable(false);

        txtCorreo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreo_usuarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("CORREO USUARIO:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("LOGIN USUARIO");

        btnAceptar_usuario.setText("INICIAR SESIÓN");
        btnAceptar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_usuarioActionPerformed(evt);
            }
        });

        lblOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOcultarMouseClicked(evt);
            }
        });

        lblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialog_usuarioLayout = new javax.swing.GroupLayout(dialog_usuario.getContentPane());
        dialog_usuario.getContentPane().setLayout(dialog_usuarioLayout);
        dialog_usuarioLayout.setHorizontalGroup(
            dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel4))
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2))
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtCorreo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3))
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtContra_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVer)
                    .addComponent(lblOcultar)))
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnAceptar_usuario))
        );
        dialog_usuarioLayout.setVerticalGroup(
            dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_usuarioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(dialog_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_usuarioLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtContra_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVer)
                    .addComponent(lblOcultar))
                .addGap(22, 22, 22)
                .addComponent(btnAceptar_usuario)
                .addGap(42, 42, 42))
        );

        dialog_admin.setMinimumSize(new java.awt.Dimension(329, 308));
        dialog_admin.setResizable(false);

        txtCorreo_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreo_adminActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("CORREO ADMINISTRADOR:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("CONTRASEÑA:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("LOGIN ADMINISTRADOR");

        btnAceptar_admin.setText("INICIAR SESIÓN");
        btnAceptar_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar_adminActionPerformed(evt);
            }
        });

        lblOcultar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercr\\Documents\\NetBeansProjects\\CamaraPrueba\\ocultarf.png")); // NOI18N
        lblOcultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOcultar1MouseClicked(evt);
            }
        });

        lblVer1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercr\\Documents\\NetBeansProjects\\CamaraPrueba\\mostrarf.png")); // NOI18N
        lblVer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVer1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialog_adminLayout = new javax.swing.GroupLayout(dialog_admin.getContentPane());
        dialog_admin.getContentPane().setLayout(dialog_adminLayout);
        dialog_adminLayout.setHorizontalGroup(
            dialog_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel7))
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5))
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtCorreo_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6))
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtContra_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(dialog_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVer1)
                    .addComponent(lblOcultar1)))
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnAceptar_admin))
        );
        dialog_adminLayout.setVerticalGroup(
            dialog_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_adminLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(txtCorreo_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addGroup(dialog_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_adminLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtContra_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVer1)
                    .addComponent(lblOcultar1))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar_admin))
        );

        dialog_registro_usuario.setMinimumSize(new java.awt.Dimension(538, 354));
        dialog_registro_usuario.setResizable(false);

        Nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_usuarioActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre");

        jLabel11.setText("Correo");

        Contra_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contra_usuarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Contraseña");

        Contra_usuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contra_usuario2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Nuevamente contraseña");

        txtRegistrar_usuario.setText("Registrar");
        txtRegistrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrar_usuarioActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Apellido Paterno");

        jLabel20.setText("Apellido Materno");

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");

        javax.swing.GroupLayout dialog_registro_usuarioLayout = new javax.swing.GroupLayout(dialog_registro_usuario.getContentPane());
        dialog_registro_usuario.getContentPane().setLayout(dialog_registro_usuarioLayout);
        dialog_registro_usuarioLayout.setHorizontalGroup(
            dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Contra_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ocultar_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrar_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Contra_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostrar_2)
                            .addComponent(ocultar_2)))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addComponent(Correo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(txtRegistrar_usuario))))
        );
        dialog_registro_usuarioLayout.setVerticalGroup(
            dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(6, 6, 6)
                .addComponent(Nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addGap(6, 6, 6)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17))
                        .addGap(4, 4, 4)
                        .addComponent(Contra_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ocultar_1)
                            .addComponent(mostrar_1))))
                .addGap(12, 12, 12)
                .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18))
                        .addGap(4, 4, 4)
                        .addComponent(Contra_usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_registro_usuarioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostrar_2)
                            .addComponent(ocultar_2))))
                .addGap(14, 14, 14)
                .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(6, 6, 6)
                .addGroup(dialog_registro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Correo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistrar_usuario))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_usuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercr\\Downloads\\Iconos\\usuario.png")); // NOI18N
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });
        add(btn_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 70, 172, 161));

        btn_administrador.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercr\\Downloads\\Iconos\\administrador.png")); // NOI18N
        btn_administrador.setToolTipText("");
        btn_administrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administradorActionPerformed(evt);
            }
        });
        add(btn_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 172, 161));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel23.setText("EMPLEADO");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel24.setText("ADMINISTRADOR");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
        dialog_usuario.setVisible(true);
        dialog_usuario.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_administradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administradorActionPerformed
        dialog_admin.setVisible(true);
        dialog_admin.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_administradorActionPerformed

    private void txtCorreo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo_usuarioActionPerformed

    private void txtCorreo_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo_adminActionPerformed

    private void btnAceptar_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_adminActionPerformed
        String correo = txtCorreo_admin.getText();
        String contrasena = new String(txtContra_admin.getPassword());

        Usuario us = new Usuario();
        boolean loginExitoso = us.verificarLogin(correo, contrasena);

        if (loginExitoso) {
            JOptionPane.showMessageDialog(this, "Login como administrador exitoso");
            Principal principal = new Principal("administrador");
            principal.setVisible(true);
            // Cierra la ventana de login 
            dialog_admin.setVisible(false);
            ((JFrame) this.getTopLevelAncestor()).dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Login fallido. Por favor, verifica tus credenciales.");
        }
    }//GEN-LAST:event_btnAceptar_adminActionPerformed

    private void btnAceptar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar_usuarioActionPerformed
        String correo = txtCorreo_usuario.getText();
        String contrasena = new String(txtContra_usuario.getPassword());

        Usuario us = new Usuario();
        boolean loginExitoso = us.verificarLogin(correo, contrasena);

        if (loginExitoso) {
            JOptionPane.showMessageDialog(this, "Login como usuario exitoso");
            Principal principal = new Principal("usuario");
            principal.setVisible(true);
            // Cierra la ventana de login actual si es un JFrame
            dialog_usuario.setVisible(false);
            java.awt.Component component = this.getTopLevelAncestor();
            if (component instanceof JFrame) {
                ((JFrame) component).dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Login fallido. Por favor, verifica tus credenciales.");
        }
    }//GEN-LAST:event_btnAceptar_usuarioActionPerformed

    private void Nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_usuarioActionPerformed

    private void Contra_usuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contra_usuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contra_usuario2ActionPerformed

    private void lblOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultarMouseClicked
        lblVer.setVisible(true);
        lblOcultar.setVisible(false);
        txtContra_usuario.setEchoChar('*');
    }//GEN-LAST:event_lblOcultarMouseClicked

    private void lblVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMouseClicked
        lblVer.setVisible(false);
        lblOcultar.setVisible(true);
        txtContra_usuario.setEchoChar((char)0);
    }//GEN-LAST:event_lblVerMouseClicked

    private void Contra_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contra_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contra_usuarioActionPerformed

    private void lblOcultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultar1MouseClicked
        lblVer1.setVisible(true);
        lblOcultar1.setVisible(false);
        txtContra_admin.setEchoChar('*');
    }//GEN-LAST:event_lblOcultar1MouseClicked

    private void lblVer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVer1MouseClicked
        lblVer1.setVisible(false);
        lblOcultar1.setVisible(true);
        txtContra_admin.setEchoChar((char)0);
    }//GEN-LAST:event_lblVer1MouseClicked

    private void txtRegistrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrar_usuarioActionPerformed
        dialog_registro_usuario.setVisible(false);
    }//GEN-LAST:event_txtRegistrar_usuarioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contra_usuario;
    private javax.swing.JTextField Contra_usuario2;
    private javax.swing.JTextField Correo_usuario;
    private javax.swing.JTextField Nombre_usuario;
    private javax.swing.JButton btnAceptar_admin;
    private javax.swing.JButton btnAceptar_usuario;
    private javax.swing.JButton btn_administrador;
    private javax.swing.JButton btn_usuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dialog_admin;
    private javax.swing.JDialog dialog_registro_usuario;
    private javax.swing.JDialog dialog_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblOcultar;
    private javax.swing.JLabel lblOcultar1;
    private javax.swing.JLabel lblVer;
    private javax.swing.JLabel lblVer1;
    private javax.swing.JLabel mostrar_1;
    private javax.swing.JLabel mostrar_2;
    private javax.swing.JLabel ocultar_1;
    private javax.swing.JLabel ocultar_2;
    private javax.swing.JPasswordField txtContra_admin;
    private javax.swing.JPasswordField txtContra_usuario;
    private javax.swing.JTextField txtCorreo_admin;
    private javax.swing.JTextField txtCorreo_usuario;
    private javax.swing.JButton txtRegistrar_usuario;
    // End of variables declaration//GEN-END:variables
}
